  
name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: sbpack push
        uses: ./
        with:
          app_name: thomasyu888/test/testing
          workflow_path: example/hello_world_workflow.cwl
          auth_token: ${{secrets.SBG_AUTH_TOKEN }}
          api_endpoint: https://cavatica-api.sbgenomics.com/v2
